### ISSUE TITLE
Configure Starrocks Cluster with custom user name and password

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#109]
For better security, 
we need to add support to configure the Starrocks cluster with custom user name and passoword.
The password could be configure from a k8s secret.

Proposed place in the helm chart values.yaml:
```
starrocksOperator:
  # provide a name for operator deployment.
  userName:
  password: 
```
https://github.com/StarRocks/starrocks-kubernetes-operator/blob/7bbec984ba1d442a5a0d18b0912230ed5c6f7b64/pkg/sub_controller/fe/fe_pod.go#L150-L151
