### ISSUE TITLE
Add support to annotate operator pod in helm chart

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#113]
This is needed for collecting logs and metrics from datadog agent.

```
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: {{ template "kube-starrocks.name" . }}-operator
        version: {{ $.Chart.Version }}
```
