### ISSUE TITLE
Clean up the values.yaml file.

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#114]
It would be great for SR team to clean up the unused values in values.yaml file.
This effort can help reduce unnecessary questions/distraction to both the chart author and helm users.

E.g.
```
starrocksCluster:
  # Provide a name for starprocks cluster
  name: ""
  namespace: ""
  # annotations for starrocks cluster
  annotations: {} <======
```
