### ISSUE TITLE
support initPassword from existing secrets

### ISSUE THREAD

**Issue by kevincai** [StarRocks/starrocks-kubernetes-operator#192]
starting from v1.7.0, we support specify init password when deploying with helm chart, the password is a plaintext configuration in the values.
```
initPassword: 
  enabled: true
  password: "mysql_password"
```

An alternative solution may be, support user to provide a secret name which contains the password, use the password from the secret, instead of plaintext in values.yaml

```
initPassword: 
  enabled: true
  password: ""
  passwordSecret: "<secretName>"
```
