### ISSUE TITLE
How to mount the sub path of PVC

### ISSUE THREAD

**Issue by xie233** [StarRocks/starrocks-kubernetes-operator#205]
We have a storage provided by cloud nfs. It's able to using PVC. My nfs storage contains redis, some app data,   we would like to collect  all starrocks data (fe-log,fe-meta,be-log) into the same directory, Is there any way to specify the subpath when mounting to container? This is my example:

```
    storageVolumes:
      - name: fe-log
        storageClassName: managed-nfs-storage
        storageSize: 10Gi
        mountPath: /opt/starrocks/fe/log
        subPath: /stardata
```

It shows the error,
``` 
unknown field "subPath" in com.starrocks.v1.StarRocksCluster.spec.starRocksFeSpec.storageVolumes
```
