### ISSUE TITLE
The hpaPolicy example is not very fitting

### ISSUE THREAD

**Issue by yandongxiao** [StarRocks/starrocks-kubernetes-operator#231]
In https://raw.githubusercontent.com/StarRocks/starrocks-kubernetes-operator/main/examples/starrocks/starrocks-fe-and-cn-with-autoscaler.yaml , the hpaPolicy example is not very fitting.

```
      hpaPolicy:
        metrics:
          - type: Resource
            resource:
              name: memory
              target:
                averageUtilization: 30
                type: Utilization
          - type: Resource
            resource:
              name: cpu
              target:
                averageUtilization: 30
                type: Utilization
        behavior:
          scaleUp:
            policies:
              - type: Pods 
                value: 1
                periodSeconds: 10
          scaleDown:
            selectPolicy: Disabled
```

1. scaleUp based on quantity, with a maximum limit of 1
2. scaleDown is not allowed
