### ISSUE TITLE
FE service annotation should not annotate fe-search headless

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#367]
## FE service annotation should not annotate fe-search headless

There might be an issue with the annotation of FE service with helm chart value file.
When add the following annotation to starrocksFESpec.service.
the current CRD/operator try to add the annotation to both  fe-search  and fe-service
However, fe-search is a clusterIP  service. Then I got the error below.
Can you adapt the operator to apply the service's annotation to fe-service?
Thank you!

## To Reproduce
On EKS where [aws-load-balancer-controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/) is installed.
Annotate the fe service in values.yaml

```
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-name: celostar
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
        service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stickiness.enabled=true,stickiness.type=source_ip
        service.beta.kubernetes.io/load-balancer-source-ranges: |
          10.16.76.70/32, 10.116.14.22/32
```
The k8s operator will print error message:
```
FeController Sync create or patch internal service namespace celostar-dic name celostar-fe-search failed, message Service "celostar-fe-search" is invalid: metadata.annotations[service.beta.kubernetes.io/load-balancer-source-ranges]: Forbidden: may only be used when `type` is 'LoadBalancer'
```
## Expected behavior

FE service annotation should not annotate fe-search headless## Please complete the following information

- Operator Version: [e.g. v1.8.6]
- Chart Name: [e.g. kube-starrocks]
- Chart Version [e.g. v1.8.6]
