### ISSUE TITLE
Prefer to use containerPort to export service node port

### ISSUE THREAD

**Issue by yandongxiao** [StarRocks/starrocks-kubernetes-operator#378]
## Describe the current behavior

When user want to export service node port, It should write following conf:
```
  service:
    type: NodePort
    ports:
      - name: http-port   # fill the name from the fe proxy service ports
        containerPort: 8080
        nodePort: 30180
        port: 8080
```

name is required field, and must keep the same with the name defined in k8s service.

But If users Start from scratch, they do not know the port.name.

## Describe the enhancement

If user specify containerPort and name, first use containerPort to match, then use name.
