### ISSUE TITLE
Operator should skip syncing the fields that is not defined in the CRD

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#384]
## Describe the bug

Currently operator consider all the fields that are not defined in CRD as `null` and try to sync the `null` value to the object.
In case where the object were created via other external controller e.g. load balancer, it will cause failure.
E.g. a fe-service loadbalancer that were provisioned by [aws load balancer controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/nlb/) will have ` loadBalancerClass: service.k8s.aws/nlb` field added by the controller. 
while the operator considers it's has `null` value and try to sync the value and fails:

```
FeController Sync create or patch external service namespace celostar-dic name celostar-fe-service failed, message Service "celostar-fe-service" is invalid: spec.loadBalancerClass: Invalid value: "null": may not change once set

StarRocksClusterReconciler reconcile sub resource reconcile failed, namespace=celostar-dic, name=celostar, controller=feController, error=Service "celostar-fe-service" is invalid: spec.loadBalancerClass: Invalid value: "null": may not change once set
```
## To Reproduce

1) Install  [aws load balancer controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/nlb/) to the k8s cluster
2) Annotate fe-service with these annotation:
```
starrocksFESpec set to
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: celostar
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stickiness.enabled=true,stickiness.type=source_ip

```

## Expected behavior
Operator should skip syncing the fields that is not defined in the CRD
## Please complete the following information

- Operator Version: [e.g. v1.8.6]
- Chart Name: [e.g. kube-starrocks]
- Chart Version [e.g. v1.8.6]
