### ISSUE TITLE
Allow using milliCPU notation for resource requests rather than integer string

### ISSUE THREAD

**Issue by inviscid** [StarRocks/starrocks-kubernetes-operator#393]
## Describe the current behavior
Currently, resource requests are required to be integer strings.  Attempting to use milliCPU notation fails.

This works:
```
starrocks:
  cn:
    cpu: '1'
    memory: 4Gi
    replicas: 1
  fe:
    cpu: '1'
    memory: 4Gi
    replicas: 3
```

This does not:
```
starrocks:
  cn:
    cpu: 500m
    memory: 4Gi
    replicas: 1
  fe:
    cpu: 500m
    memory: 4Gi
    replicas: 3
```

## Describe the enhancement
Allow use of milliCPU notation and pass through to the underlying statefulset and pod resource requests as specified.

## Additional context
N/A

**Comment by yandongxiao** [comment]
Operator has supported milliCPU from the beginning. What version is your Operator, and what error did it report?
This is from StarRocksCluster CR.
```
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
```
