### ISSUE TITLE
starrocks helm chart cannot merge feEnvVars and beEnvVars

### ISSUE THREAD

**Issue by mingmxu** [StarRocks/starrocks-kubernetes-operator#395]
When rendering with multiple values files, the value of feEnvVars is **replaced** instead of **merged**, same for beEnvVars.

Take the example as below:
```
# values.yaml
  starrocksBeSpec:
    beEnvVars:
      - name: env
        value: "env"
```

```
# values_1.yaml
  starrocksBeSpec:
    beEnvVars:
      - name: env1
        value: "env1"
```

I expect to see,
```
    beEnvVars:
      - name: env
        value: "env"
      - name: env1
        value: env1
```   

However it's rendered as
```
    beEnvVars:
      - name: env1
        value: env1
```
