### ISSUE TITLE
StarRocks Operator always checks for Auto Scaling, even if the config is not present in the StarRocksCluster

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks-kubernetes-operator#420]
StarRocks Operator always checks for Auto Scaling, even if the config is not present in the StarRocksCluster. The problem here is that newer versions of Kubernetes come with v2 HPA rather than v2/beta2, which is the default. There is no way to disable this check, so I'm forced to keep a static HPA config for the cluster.

@nferrario

**Comment by yandongxiao** [comment]
Which Operator version do you use? The newest Operator version has supported v2 HPA.

And what do you mean? 
```
StarRocks Operator always checks for Auto Scaling, even if the config is not present in the StarRocksCluster.
```
Is Operator's reconciling action in infinite loop ?

**Comment by nferrario** [comment]
I'm using the latest 1.9.0 (and started with 1.8.8). The issue occurs on newer Kubernetes versions where HPA v2/beta2 is not available, which is StarRocks' Operator default. 

If I want to use HPA, I can definitely set the version v2 in StarRocksCluster and it works. The problem is when I don't want to use HPA (unset/empty `autoScalingPolicy`) and the StarRocks Operator still tries to find HPA v2/beta2, which of course isn't available in the cluster.

**Comment by yandongxiao** [comment]
I didn't reproduce the error. 

In fact, the Operator will detect the version of the API Server at startup.
https://github.com/StarRocks/starrocks-kubernetes-operator/blob/7ddf5a592f9caf19652804f85ecb047db4844a4f/pkg/k8sutils/k8sutils.go#L299

When creating or deleting an HPA object, if no version is specified, it will also select the appropriate HPA version according to the version of the API Server.

https://github.com/StarRocks/starrocks-kubernetes-operator/blob/7ddf5a592f9caf19652804f85ecb047db4844a4f/pkg/apis/starrocks/v1/auto_scale.go#L77

**Comment by yandongxiao** [comment]
This is my values.yaml.
```
operator:
  starrocksOperator:
    image:
      repository: starrocks/operator
      tag: v1.9.0
    imagePullPolicy: IfNotPresent
starrocks:
  initPassword:
    enabled: true
    password: "123456"
  metrics:
    serviceMonitor:
      enabled: true
  starrocksBeSpec:
    configMapInfo:
      configMapName: kube-starrocks-be-cm
      resolveKey: be.conf
    image:
      repository: starrocks/be-ubuntu
      tag: 3.2.2
    replicas: 1
    resources:
      limits:
        cpu: 8
        memory: 8Gi
      requests:
        cpu: 101m
        memory: 100Mi
    service:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8040"
        prometheus.io/scrape: "true"
      type: ClusterIP
    storageSpec:
      logStorageSize: 1Gi
      name: be-storage
      storageSize: 10Gi
  starrocksCluster:
    enabledBe: true
    enabledCn: true
  starrocksCnSpec:
    image:
      repository: starrocks/cn-ubuntu
      tag: 3.2.2
    replicas: 0
    resources:
      limits:
        cpu: 8
        memory: 8Gi
      requests:
        cpu: 101m
        memory: 100Mi
    service:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8040"
        prometheus.io/scrape: "true"
#    autoScalingPolicy:
#      version: v2
#      maxReplicas: 2
#      minReplicas: 1
#      hpaPolicy:
#        behavior:
#          scaleUp:
#            policies:
#              - type: Pods
#                value: 1
#                periodSeconds: 10
#          scaleDown:
#            selectPolicy: Disabled
#        metrics:
#          - type: Resource
#            resource:
#              name: memory
#              target:
#                averageUtilization: 60
#                type: Utilization
#          - type: Resource
#            resource:
#              name: cpu
#              target:
#                averageUtilization: 60
#                type: Utilization
  starrocksFESpec:
    image:
      repository: starrocks/fe-ubuntu
      tag: 3.2.2
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 200Mi
    service:
      annotations:
        aaa: bbb
        prometheus.io/path: /metrics
        prometheus.io/port: "8030"
        prometheus.io/scrape: "true"
      type: LoadBalancer
    storageSpec:
      logStorageSize: 1Gi
      name: fe-storage
      storageSize: 10Gi
```
