### ISSUE TITLE
Support `imagePullSecrets` for pulling image from private repos

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#44]
Can we add the support  of `imagePullSecrets` for pulling image from private repos.

We need this support for all services: fe/be/cn/operator.
On the Helm Chart value file, it could be a filed under `image` .e.g `image.imagePullSecrets`
https://github.com/StarRocks/helm-charts/blob/main/charts/kube-starrocks/values.yaml#LL16-L19C14

**Comment by dengliu** [comment]
@kevincai @shileifu  @imay 
here is an example of how other operator/helm chart support the configurations of image pull secret and pullPolicy
```
prometheusScrape: true
image:
  repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
  # If unset use v + .Charts.appVersion
  tag: ""
  sha: ""
  pullPolicy: IfNotPresent

imagePullSecrets: [] <==============
```
https://github.com/prometheus-community/helm-charts/blob/21ed9ed127a41802ddd7f4854d15467e78c84dc3/charts/kube-state-metrics/values.yaml#L10
