### ISSUE TITLE
Insufficient documentation on Azure Kubernetes Deployment with Helm 

### ISSUE THREAD

**Issue by delsehi** [StarRocks/starrocks-kubernetes-operator#447]
## Describe the issue with documentation

I'm having issues following the guides to deploy to AKS on a standard SKU using Helm. 

I've attempted running just 
"helm install starrocks starrocks-community/kube-starrocks" 
without any configuration. 

```
NAME                                     READY   STATUS    RESTARTS   AGE     IP            NODE                                NOMINATED NODE   READINESS GATES
kube-starrocks-fe-0                      0/1     Pending   0          3m49s   <none>        <none>                              <none>           <none>
kube-starrocks-operator-cf574b68-j7x4f   1/1     Running   0          4m7s    10.244.1.20   aks-agentpool-89422478-vmss000001   <none>           <none>
```
The FE instance is stuck forever in pending. 
Running `kubectl describe pods kube-starrocks-fe-0`
```
Events:
  Type     Reason             Age    From                Message
  ----     ------             ----   ----                -------
  Warning  FailedScheduling   4m36s  default-scheduler   0/2 nodes are available: 2 Insufficient cpu. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod..
  Normal   NotTriggerScaleUp  4m32s  cluster-autoscaler  pod didn't trigger scale-up: 1 Insufficient cpu

```

I've also attempted using a custom yaml file (I want to use shared-data config)

```yaml 

operator:
  timeZone: Europe/Stockholm
  global:
    rbac:
      create: true
      serviceAccount:
        name: "starrocks"

starrocks: 
  initPassword:
    enabled: false
    # password: "Some password, disabled because this errored"
  
  # TimeZone is used to set the environment variable TZ for pod, with Asia/Shanghai as the default.
  timeZone: Europe/Stockholm
  starrocksCluster:
    # specify the cn deploy or not.
    enabledBe: false
    enabledCn: true

  starrocksFESpec:
    service:
    config: |
      LOG_DIR = ${STARROCKS_HOME}/log
      DATE = "$(date +%Y%m%d-%H%M%S)"
      JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:${LOG_DIR}/fe.gc.log.$DATE"
      JAVA_OPTS_FOR_JDK_9="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xlog:gc*:${LOG_DIR}/fe.gc.log.$DATE:time"
      JAVA_OPTS_FOR_JDK_11="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseG1GC -Xlog:gc*:${LOG_DIR}/fe.gc.log.$DATE:time"
      http_port = 8030
      rpc_port = 9020
      query_port = 9030
      edit_log_port = 9010
      mysql_service_nio_enabled = true
      sys_log_level = INFO
      run_mode = shared_data
      cloud_native_storage_type = AZBLOB
      azure_blob_path = < A CONTAINER :) >
      azure_blob_endpoint = https://MYBLOB.blob.core.windows.net
      azure_blob_shared_key = <MY KEY>

  starrocksCnSpec:
    service:
    config: |
      sys_log_level = INFO
      # ports for admin, web, heartbeat service
      thrift_port = 9060
      webserver_port = 8040
      heartbeat_service_port = 9050
      brpc_port = 8060

```

Are there any additional steps that I'm missing?

**Comment by delsehi** [comment]
Sorry for the issue. 

Slimming down the memory and cpu request in resources helped. 

```yaml

**Comment by delsehi** [comment]
Sorry for the issue. 

Slimming down the memory and cpu request in resources helped. 

```yaml
    resources:
      requests:
        cpu: 2
        memory: 100Mi
      # If you want to remove one resource limit, e.g. cpu, you can it to cpu: "unlimited".
      limits:
        cpu: 8
        memory: 8Gi
```
