### ISSUE TITLE
[Enhancement] Use HTTP endpoint for Readiness/Liveness Probes

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#47]
The current implementation is using tcpSocket for `livenessProbe/readinessProbe/startupProbe`
This is a less preferred way of implementing Readiness/Liveness probe.
Detailed discussion can be found in this tech blog: 
[Stop Using TCP Health Checks for Kubernetes Application](https://speedscale.com/stop-using-tcp-health-checks-for-kubernetes/)

Suggest using the http endpoint for k8s probes
Starrocks Official Doc: [Check the health status of a cluster]( https://docs.starrocks.io/en-us/latest/administration/Cluster_administration#check-the-health-status-of-a-cluster 
)

```
      livenessProbe:
        tcpSocket:
          port: 9050
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        tcpSocket:
          port: 9060
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      startupProbe:
        tcpSocket:
          port: 8060
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 60
```
