### ISSUE TITLE
Can't change an existing cluster to `hostPath`

### ISSUE THREAD

**Issue by nferrario** [StarRocks/starrocks-kubernetes-operator#485]
## Describe the bug

Changing the storage configuration for an existing cluster gives the following error:

```
2024-03-20T14:22:28.787Z    ERROR    StarRocksClusterReconciler    sub controller reconciles spec failed    {"name": "starrocks", "namespace": "starrocks", "subController": "cnController", "error": "StatefulSet.apps \"starrocks-cn\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden"}
github.com/StarRocks/starrocks-kubernetes-operator/pkg/controllers.(*StarRocksClusterReconciler).Reconcile
    /go/src/app/pkg/controllers/starrockscluster_controller.go:94
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
    /go/src/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /go/src/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/src/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /go/src/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234
2024-03-20T14:22:28.817Z    ERROR    Reconciler error    {"controller": "starrockscluster", "controllerGroup": "starrocks.com", "controllerKind": "StarRocksCluster", "StarRocksCluster": {"name":"starrocks","namespace":"starrocks"}, "namespace": "starrocks", "name": "starrocks", "reconcileID": "a003748f-57dd-454b-a79c-2bd1de0636b3", "error": "StatefulSet.apps \"starrocks-cn\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /go/src/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:326
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/src/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /go/src/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234
```

This is probably expected as Kubernetes tends to be strict. However, if I manually delete the CN Stateful Set, the StarRocks Operator creates a new one with the **old** storage config.

## To Reproduce

1. Create a cluster that uses PVCs:

  ```
starRocksCnSpec:
    image: starrocks/cn-ubuntu:3.2.4
    replicas: 3
    requests:
      cpu: 7700m
      memory: 29Gi
    limits:
      cpu: 7700m
      memory: 29Gi
    cnEnvVars:
      - name: LOG_CONSOLE
        value: "1"
    configMapInfo:
      configMapName: starrocks-cn
      resolveKey: cn.conf
    storageVolumes:
      - name: cn-cache
        storageClassName: ephemeral
        strageSize: 440Gi
        mountPath: /storage
```

2. Update the CRD to use HostPath instead
  ```
starRocksCnSpec:
    image: starrocks/cn-ubuntu:3.2.4
    replicas: 3
    requests:
      cpu: 7700m
      memory: 29Gi
    limits:
      cpu: 7700m
      memory: 29Gi
    cnEnvVars:
      - name: LOG_CONSOLE
        value: "1"
    configMapInfo:
      configMapName: starrocks-cn
      resolveKey: cn.conf
    storageVolumes:
      - name: cn-cache
        hostPath:
          path: /storage
        mountPath: /storage
```

3. See the error in the StarRocks Operator logs
4. Manually delete the Stateful Set
5. Stateful set reappears with PVC instead of HostPath

## Expected behavior

Option A: Operator creates a new Stateful Set (dangerous)
Option B: Operator respects the latest StarRocksCluster definition and recreates a manually deleted Stateful Set with HostPath.

## Please complete the following information

- Operator Version: v1.9.3
