### ISSUE TITLE
Not able to deploy when mount with hostPath 

### ISSUE THREAD

**Issue by sheltonsuen** [StarRocks/starrocks-kubernetes-operator#520]
## Describe the bug

When deploy the starrocks cluster with hostPath storage, the helm charts get json parse error

## To Reproduce

1. edit charts to mount hostPath
2. helm install
3. get json parse error

## Expected behavior
SR cluster deployed

## Please complete the following information

- Operator Version:  1.9.6
- Chart Name: kube-starrocks
- Chart Version 1.9.6

**Comment by yandongxiao** [comment]
Can you show me your values.yaml to let me reproduce it? I tried myself by using the following values.yaml && v1.9.6 kube-starrocks helm chart.

```
operator:
  starrocksOperator:
    image:
      repository: starrocks/operator
      tag: v1.9.6
    imagePullPolicy: IfNotPresent
starrocks:
  initPassword:
    enabled: true
    password: "123456"
  metrics:
    serviceMonitor:
      enabled: true
  starrocksBeSpec:
    hostPaths:
    - name: aaa
      mountPath: /tmp
      hostPath:
        path: /tmp
    beEnvVars:
    - name: LOG_CONSOLE
      value: "1"
    image:
      repository: starrocks/be-ubuntu
      tag: 3.2.2
    replicas: 1
    resources:
      limits:
        cpu: 8
        memory: 8Gi
      requests:
        cpu: 101m
        memory: 100Mi
    service:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8040"
        prometheus.io/scrape: "true"
      type: ClusterIP
    storageSpec:
      logStorageSize: 1Gi
      name: be-storage
      storageSize: 10Gi
  starrocksCluster:
    enabledBe: true
    enabledCn: true
  starrocksCnSpec:
    hostPaths:
    - name: aaa
      mountPath: /tmp
      hostPath:
        path: /tmp
    cnEnvVars:
    - name: LOG_CONSOLE
      value: "1"
    image:
      repository: starrocks/cn-ubuntu
      tag: 3.2.2-5
    replicas: 0
    resources:
      limits:
        cpu: 8
        memory: 8Gi
      requests:
        cpu: 101m
        memory: 100Mi
    service:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8040"
        prometheus.io/scrape: "true"
    startupProbeFailureSeconds: 30000
  starrocksFESpec:
    hostPaths:
    - name: aaa
      mountPath: /tmp
      hostPath:
        path: /tmp
    feEnvVars:
    - name: LOG_CONSOLE
      value: "1"
    image:
      repository: starrocks/fe-ubuntu
      tag: 3.2.2
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 200Mi
    service:
      annotations:
        aaa: bbb
        prometheus.io/path: /metrics
        prometheus.io/port: "8030"
        prometheus.io/scrape: "true"
      type: LoadBalancer
    storageSpec:
      logStorageSize: 1Gi
      name: fe-storage
      storageSize: 10Gi

```
