### ISSUE TITLE
[Feature] Support configure imagePullSecrets and annotation for the global SA

### ISSUE THREAD

**Issue by dengliu** [StarRocks/starrocks-kubernetes-operator#53]
We need these two fields be configurable via helm chart` values.yaml`
- `imagePullSecrets`: to pull image from private registry
- `annotations`:  to assume a role from an AWS account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-starrocks
  namespace: celostar
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxx:role/yyy <=========
imagePullSecrets:
  - name: docker-ecr-pull <==============
secrets:
  - name: kube-starrocks-dockercfg-h5wzz

```
