### ISSUE TITLE
How can I set the namespace when deploying with Helm

### ISSUE THREAD

**Issue by DanRoscigno** [StarRocks/starrocks-kubernetes-operator#559]
I can set the namespace for the operator in overrides.yaml:

```yaml
operator:
    starrocksOperator:
        namespaceOverride: sr-operator
```

But I can't figure out how to set the namespace for a starrocksCluster. From reading the default values.yaml I thought it would be like below, but the default namespace gets used:

```yaml
starrocks:
    starrocksCluster:
        namespace: quickstart
```
