### ISSUE TITLE
be startup faild

### ISSUE THREAD

**Issue by happyi** [StarRocks/starrocks-kubernetes-operator#574]
## Describe the bug

FE work well BE pod start faild 

Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/starrocks/be_entrypoint.sh": stat /opt/starrocks/be_entrypoint.sh: no such file or directory: unknown

```

# fe config
apiVersion: v1
kind: ConfigMap
metadata:
  name: starrockscluster-fe-cm
  namespace: starrocks
  labels:
    cluster: starrockscluster
data:
  fe.conf: |
    LOG_DIR = ${STARROCKS_HOME}/log
    DATE = "$(date +%Y%m%d-%H%M%S)"
    JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Xmx61440m -XX:+UseG1GC -Xlog:gc*:${LOG_DIR}/fe.gc.log.$DATE:time"
    http_port = 8030
    rpc_port = 9020
    query_port = 9030
    edit_log_port = 9010
    mysql_service_nio_enabled = true
    sys_log_level = INFO

---

# be config
apiVersion: v1
kind: ConfigMap
metadata:
  name: starrockscluster-be-cm
  namespace: starrocks
  labels:
    cluster: starrockscluster
data:
  be.conf: |
    be_port = 9060
    webserver_port = 8040
    heartbeat_service_port = 9050
    brpc_port = 8060
    sys_log_level = INFO
    default_rowset_type = beta

---

apiVersion: starrocks.com/v1
kind: StarRocksCluster
metadata:
  name: kube-starrocks
  namespace: starrocks
  labels:
    cluster: starrocks
spec:
  starRocksFeSpec:
    image: "starrocks/fe-ubuntu:3.3.1"
    replicas: 1
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 8
      memory: 16Gi
    configMapInfo:
      configMapName: starrockscluster-fe-cm
      resolveKey: fe.conf
    storageVolumes:
    - name: fe-storage-meta
      storageClassName: hostPath  # standard-rwo is the default storageClassName in GKE.
      hostPath:
        path: /data/starrocks/fe/meta
      mountPath: /opt/starrocks/fe/meta
    - name: fe-storage-log
      storageClassName: hostPath
      hostPath:
        path: /data/starrocks/fe/log
      mountPath: /opt/starrocks/fe/log
  starRocksBeSpec:
    image: "starrocks/be-ubuntu:3.3.1"
    replicas: 1
    limits:
      cpu: 16
      memory: 64Gi
    requests:
      cpu: 16
      memory: 64Gi
    configMapInfo:
      configMapName: starrockscluster-be-cm
      resolveKey: be.conf  
    storageVolumes:
    - name: be-storage-data
      storageClassName: hostPath
      hostPath:
        path: /data/starrocks/be/storage
      mountPath: /opt/starrocks/be/storage
    - name: be-storage-log
      storageClassName: hostPath
      hostPath:
        path: /data/starrocks/be/log
      mountPath: /opt/starrocks/be/log


```

## Please complete the following information

- Operator Version: 1.9.2
- FE Version:3.3.1
- BE Version:3.3.1
