### ISSUE TITLE
Operator should not create the default data storage volume when deploying BE with multiple volumes

### ISSUE THREAD

**Issue by yandongxiao** [StarRocks/starrocks-kubernetes-operator#611]
## Describe the bug

```
operator:
  starrocksOperator:
    image:
      repository: starrocks/operator
      tag: v1.9.10
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 1m
        memory: 20Mi
starrocks:
  starrocksBeSpec:
    beEnvVars:
    config: |
      be_port = 9060
      webserver_port = 8040
      heartbeat_service_port = 9050
      brpc_port = 8060
      sys_log_level = INFO
      default_rowset_type = beta
      storage_root_path = /opt/starrocks/be/storage0;/opt/starrocks/be/storage1
    image:
      repository: starrocks/be-ubuntu
      tag: 3.2.2
    replicas: 1
    resources:
      limits:
        cpu: 8
        memory: 8Gi
      requests:
        cpu: 1m
        memory: 10Mi
    storageSpec:
      logStorageSize: 1Gi
      name: be
      storageCount: 2
      storageSize: 10Gi
  starrocksCluster:
    enabledBe: true
    enabledCn: true
  starrocksCnSpec:
    cnEnvVars:
    config: |
      sys_log_level = INFO
      # ports for admin, web, heartbeat service
      thrift_port = 9060
      webserver_port = 8040
      heartbeat_service_port = 9050
      brpc_port = 8060
      storage_root_path = /opt/starrocks/cn/storage0;/opt/starrocks/cn/storage1;/opt/starrocks/cn/storage2
    image:
      repository: starrocks/cn-ubuntu
      tag: 3.2.2
    replicas: 1
    resources:
      limits:
        cpu: 8
        memory: 8Gi
      requests:
        cpu: 1m
        memory: 10Mi
    storageSpec:
      logStorageSize: 1Gi
      name: cn
      storageCount: 3
      storageSize: 10Gi
  starrocksFESpec:
    image:
      repository: starrocks/fe-ubuntu
      tag: 3.2.2
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 1m
        memory: 20Mi
    storageSpec:
      logStorageSize: 1Gi
      name: fe-storage
      storageSize: 10Gi
```

After install the helm chart, there will an extra useless volume for BE.

```
  volumes:
  - name: be1-data
    persistentVolumeClaim:
      claimName: be1-data-kube-starrocks-be-0
  - name: be-log
    persistentVolumeClaim:
      claimName: be-log-kube-starrocks-be-0
  - name: be0-data
    persistentVolumeClaim:
      claimName: be0-data-kube-starrocks-be-0
  - emptyDir: {}
    name: be-data
  - configMap:
      defaultMode: 420
      name: kube-starrocks-be-cm
    name: kube-starrocks-be-cm
```

## Expected behavior

Remove the extra useless `be-data` volume

## Please complete the following information

- Operator Version: v1.9.10
- Chart Name: kube-starrocks
- Chart Version v1.9.10
