### ISSUE TITLE
How to pass custom configuration for sidecar containers

### ISSUE THREAD

**Issue by pcheliniy** [StarRocks/starrocks-kubernetes-operator#626]
## Describe the issue with documentation
The StarRocksCluster CRD allows configuring volume mounts for sidecar containers using:
`.spec.starRocksFeSpec.sidecars.volumeMounts`
The actual volume creation for these mounts relies on:
`.spec.starRocksFeSpec.configMaps`, and can be done like this
```
  starRocksFeSpec:
    configMaps:
    - name: starrocks-fluentbit-sidecar
      mountPath: /opt/fluentbit/fluent-bit.conf
      subPath: fluent-bit.conf
```
The issue arises when configMaps are used to create volumes. 
The generated volume names include numbered suffixes:
```
volumes:
  - configMap:
      defaultMode: 420
      name: starrocks-fluentbit-sidecar
    name: starrocks-fluentbit-sidecar-1125
```
Each time the StatefulSet (STS) is recreated, the suffix changes, requiring manual updates to the sidecar’s `volumeMounts` configuration to match the new name, like
```
    sidecars:
    - name: fluent-bit
      image: fluent/fluent-bit:latest
      volumeMounts:
      - name: fe-storage-log
        mountPath: /var/log/app
        readOnly: true
      - name: starrocks-fluentbit-sidecar-1125
        mountPath: /fluent-bit/etc/fluent-bit.conf
        subPath: fluent-bit.conf
        readOnly: true
```

## Suggested change
Are there recommended ways to handle this issue? 
If there is already an official solution or a best practice for handling this scenario, could you add it to the documentation or point to it?

## Additional context
This issue makes automated deployment and management of StarRocks clusters more difficult, as each STS recreation forces manual intervention. Looking for any guidance or a potential fix for this.

**Comment by yandongxiao** [comment]
This is a good question. Initially, we did not consider exposing the `sidecars` field or allowing users to set `volumeMounts` themselves in our design, so we added a hash value to the volume name to prevent conflicts. However, based on the current situation, I think removing the hash part may be a good option. For existing clusters, this change would result in service restarts.

@kevincai Do you have any sugesstions?

**Comment by yandongxiao** [comment]
In order to maintain backward compatibility, we have provided a parameter for Operator to control whether to add a hash suffix to the volume name. @pcheliniy PTAL.

**Comment by pcheliniy** [comment]
@yandongxiao Looks good, but you mentioned above that this behaviour was added to avoid naming conflicts.
Does this only apply to cases when manually created volumes have the same name as automatically generated ones, or you have already seen other specific scenarios where conflicts may occur?

**Comment by yandongxiao** [comment]
This PR is for users who want to mount their configMap or Secret. I think we may have been a bit overzealous when implementing this feature initially, as we haven't encountered any cases where users have used the same name when configuring configMaps or Secrets. For example:
```
    configMaps:
    - name: xxx
      mountPath: /opt/starrocks/be/conf/hadoop_env.sh
      subPath: hadoop_env.sh
    - name: xxx
      mountPath: /opt/starrocks/be/conf/core-site.xml
      subPath: core-site.xml
```
