### ISSUE TITLE
Support mounting secrets, configmaps and volumes without random suffix

### ISSUE THREAD

**Issue by SHaaD94** [StarRocks/starrocks-kubernetes-operator#634]
## Describe the problem

I need to mount a secret into the init container of FE. So I use `secrets` as
```
    secrets:
    - mountPath: /etc/mysecret
      name: mysecret
      subPath: ""  
```
It mounts volume but adds random suffix to it's name, so I can't mount it into the init container:
```
  - name: mysecret-8654
    secret:
      defaultMode: 420
      secretName: mysecret
```

## Describe the solution you'd like

Option 1 - add flag to the volume/configmap/secret definition to not append suffix, so the name would remain deterministic.
Option 2 - support passing described volumes/configmaps/secrets in init containers
