### ISSUE TITLE
Add annotations config for service

### ISSUE THREAD

**Issue by Abel-Liu** [StarRocks/starrocks-kubernetes-operator#77]
Hi team,

Can I set service annotations in config, like:
```
apiVersion: starrocks.com/v1alpha1
kind: StarRocksCluster
metadata:
  name: example
  namespace: starrocks
spec:
  starRocksFeSpec:
    service:
      type: LoadBalance
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

Thanks.
