### ISSUE TITLE
Kubernetes   starrocks 2.5.4 be  errors

### ISSUE THREAD

**Issue by happyi** [StarRocks/starrocks-kubernetes-operator#92]
env：    Kubernetes  v1.26.1
operator:   starrocks/operator:latest    
deployment:  starrocks/fe-ubuntu:2.5.4    starrocks/be-ubuntu:2.5.4

fe work well , be can't be started

[Mon Apr 17 08:00:50 UTC 2023] Empty $CONFIGMAP_MOUNT_PATH env var, skip it!
[Mon Apr 17 08:00:50 UTC 2023] Add myself (starrockscluster-be-0.starrockscluster-be-search.open.svc.k8s.com:9050) into FE ...
ERROR 1064 (HY000) at line 1: Unexpected exception: Same backend already exists[starrockscluster-be-0.starrockscluster-be-search.open.svc.k8s.com:9050]
[Mon Apr 17 08:00:50 UTC 2023] run start_be.sh
/opt/starrocks/be/bin/start_backend.sh: line 185:   807 Illegal instruction     (core dumped) ${START_BE_CMD} "$@" >> ${LOG_FILE} 2>&1 < /dev/null

**Comment by kevincai** [comment]
please check your cpu info (/proc/cpuinfo)

by default, starrocks_be requires cpu to support `avx2`.

**Comment by welyss** [comment]
same problem.
``` 
[root@localhost starrocks]# kubectl logs starrockscluster-be-0
[Wed May 31 00:56:20 UTC 2023] Empty $CONFIGMAP_MOUNT_PATH env var, skip it!
[Wed May 31 00:56:20 UTC 2023] Add myself (starrockscluster-be-0.starrockscluster-be-search.starrocks.svc.cluster.local:9050) into FE ...
ERROR 1064 (HY000) at line 1: Unexpected exception: Same backend already exists[starrockscluster-be-0.starrockscluster-be-search.starrocks.svc.cluster.local:9050]
[Wed May 31 00:56:20 UTC 2023] run start_be.sh
/opt/starrocks/be/bin/start_backend.sh: line 185:   808 Illegal instruction     (core dumped) ${START_BE_CMD} "$@" >> ${LOG_FILE} 2>&1 < /dev/null
```

and k8s node already enable avx2.

```
[root@localhost starrocks]# kubectl get pod -o wide
NAME                                    READY   STATUS             RESTARTS   AGE   IP            NODE                NOMINATED NODE   READINESS GATES
starrocks-controller-79b5f48bf6-bkx48   1/1     Running            2          20h   10.42.5.102   rancher2-worker7    <none>           <none>
starrockscluster-be-0                   0/1     CrashLoopBackOff   16         61m   10.42.24.42   rancher2-worker15   <none>           <none>
starrockscluster-be-1                   0/1     CrashLoopBackOff   211        17h   10.42.18.89   rancher2-worker10   <none>           <none>
starrockscluster-be-2                   0/1     CrashLoopBackOff   210        17h   10.42.19.53   rancher2-worker11   <none>           <none>
starrockscluster-fe-0                   1/1     Running            0          17h   10.42.20.54   rancher2-worker12   <none>           <none>
starrockscluster-fe-1                   1/1     Running            0          17h   10.42.23.37   rancher2-worker14   <none>           <none>
starrockscluster-fe-2                   1/1     Running            0          17h   10.42.21.49   rancher2-worker13   <none>           <none>
```

on rancher2-worker15:

```
[root@rancher2-worker15 ~]# hostname
rancher2-worker15
[root@rancher2-worker15 ~]# lscpu | grep Flags|grep avx2
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni ssse3 cx16 sse4_1 sse4_2 x2apic avx hypervisor lahf_lm cpuid_fault pti avx2 bmi2
```

on rancher2-worker10:
```
[root@rancher2-worker10 ~]# hostname
rancher2-worker10
[root@rancher2-worker10 ~]# lscpu | grep Flags|grep avx2
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni ssse3 cx16 sse4_1 sse4_2 x2apic avx hypervisor lahf_lm cpuid_fault pti avx2 bmi2
```

on rancher2-worker11:
```
[root@rancher2-worker11 ~]# hostname
rancher2-worker11
[root@rancher2-worker11 ~]# lscpu | grep Flags|grep avx2
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni ssse3 cx16 sse4_1 sse4_2 x2apic avx hypervisor lahf_lm cpuid_fault pti avx2 bmi2
```

starrocks-fe-and-be.yaml:

```
apiVersion: starrocks.com/v1alpha1
kind: StarRocksCluster
metadata:
  name: starrockscluster
  namespace: starrocks
spec:
  starRocksFeSpec:
    image: starrocks/fe-ubuntu:2.5.4
    replicas: 3
    requests:
      cpu: 1
      memory: 3Gi
    nodeSelector:
      dedicated: starrocks
#    affinity:
#      nodeAffinity:
#        preferredDuringSchedulingIgnoredDuringExecution:
#        - weight: 1
#          preference:
#            matchExpressions:
#            - key: dedicated
#              operator: In
#              values:
#              - starrocks
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "starrocks"
        effect: "NoSchedule"
    storageVolumes:
      - name: fe-meta
        storageClassName: ceph-dba
        storageSize: 10Gi
        mountPath: /opt/starrocks/fe/meta # overwrite the default meta path
  starRocksBeSpec:
    image: starrocks/be-ubuntu:2.5.4
    replicas: 3
    requests:
      cpu: 1
      memory: 3Gi
    nodeSelector:
      dedicated: starrocks
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "starrocks"
        effect: "NoSchedule"
    storageVolumes:
      - name: be-data
        storageClassName: ceph-dba
        storageSize: 30Gi
        mountPath: /opt/starrocks/be/storage # overwrite the default data path

```
help

**Comment by kevincai** [comment]
@welyss are you able to apply following pod spec and then manual start the BE process, to get the detailed error log

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: starrocks-be-single-pod
spec:
  containers:
  - args:
    - "86400"
    command:
    - sleep
    image: 172.26.92.142:5000/starrocks/be-ubuntu:2.5.6
    imagePullPolicy: IfNotPresent
    name: be-single-pod
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 3Gi
```

After the pod is running, run following command to manual start the be process
```shell
kubectl exec -it starrocks-be-single-pod  -- /opt/starrocks/be/bin/start_be.sh
```
This command is expected to crash with the same error as you experienced.

And then please send us the following log files `/opt/starrocks/be/log/be.out` `/opt/starrocks/be/log/be.INFO`

**Comment by welyss** [comment]
@kevincai , thanks reply.
```
[root@localhost starrocks]# cat starrocks-be-single-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: starrocks-be-single-pod
  namespace: starrocks
spec:
  containers:
  - args:
    - "86400"
    command:
    - sleep
    image: starrocks/be-ubuntu:2.5.4
    imagePullPolicy: IfNotPresent
    name: be-single-pod
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 3Gi
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "starrocks"
    effect: "NoSchedule"
  nodeSelector:
    dedicated: starrocks
```

```
[root@localhost starrocks]# kubectl get pod starrocks-be-single-pod -o wide
NAME                      READY   STATUS    RESTARTS   AGE   IP            NODE                NOMINATED NODE   READINESS GATES
starrocks-be-single-pod   1/1     Running   0          29m   10.42.24.43   rancher2-worker15   <none>           <none>
```

then run the command:
```
[root@localhost starrocks]# kubectl exec -it starrocks-be-single-pod -- /opt/starrocks/be/bin/start_be.sh
/opt/starrocks/be/bin/start_backend.sh: line 185:   797 Illegal instruction     (core dumped) ${START_BE_CMD} "$@" >> ${LOG_FILE} 2>&1 < /dev/null
command terminated with exit code 132
```

here is log:
```
[root@localhost starrocks]# kubectl exec -it starrocks-be-single-pod -- /bin/bash
root@starrocks-be-single-pod:/opt/starrocks# cat /opt/starrocks/be/log/be.out
start time: Wed May 31 06:17:45 UTC 2023
root@starrocks-be-single-pod:/opt/starrocks# cat /opt/starrocks/be/log/be.INFO
cat: /opt/starrocks/be/log/be.INFO: No such file or directory
```
